### ISSUE TITLE
Everything ok but still not synced

### ISSUE THREAD

**Issue by fuatkumru** [davidsantos-br/ETS2Sync-Helper-4#40] opened 2018-11-20 16:44 UTC
Like i said. I started sync helper. Settings is ok save is ok. Clicking sync botton works perfectly. Downloading the jobs. it says sync complate but all i'm getting is normal 5 hour remaining jobs and not sycned with my friend. Can you help me?

**Comment by CiprianN23** [comment] 2018-11-20 16:55
The software is no longer working with 1.32 update of the games
Check #38 and you will find out more.

**Comment by DaviMedrade** [comment] 2018-12-29 18:48
Duplicate of #38

**Closed as completed by DaviMedrade** 2018-12-29 18:48 UTC
