### ISSUE TITLE
Not working with ETS2/ATS 1.33 /  Não trabalhando com ETS2 / ATS 1.33

### ISSUE THREAD

**Issue by HolcombD** [davidsantos-br/ETS2Sync-Helper-4#42] opened 2018-12-14 19:14 UTC
its been a while since its been updated and it is hard for people to have proper fun.

tem sido um tempo desde a sua atualização e é difícil para as pessoas se divertirem adequadamente.

**Comment by wolf0958** [comment] 2018-12-14 23:42
Yes please update this great program. Believe me it is missed by many that play ETS 2 and ATS. Any word on progress or is the program not able to.be updated any longer. David please advise. Thank you for making the sims better for all of us that play them

**Comment by DaviMedrade** [comment] 2018-12-29 18:49
Duplicate of #38

**Closed as completed by DaviMedrade** 2018-12-29 18:49 UTC
