### ISSUE TITLE
Caught unhandled unknown exception, terminating

### ISSUE THREAD

**Issue by VortexLife** [davidsantos-br/ETS2Sync-Helper-4#33] opened 2018-05-20 23:42 UTC
I keep getting this error whenever i try to sync jobs, i'm guessing this is needing updated?

**Comment by DaviMedrade** [comment] 2018-05-23 14:30
Probably a duplicate of #31. If this still happens after #31 is closed, please reopen.

**Closed as completed by DaviMedrade** 2018-05-23 14:30 UTC
Labels: duplicate
