### ISSUE TITLE
5.3.1 truck taking damage 

### ISSUE THREAD

**Issue by MAURICE598** [davidsantos-br/ETS2Sync-Helper-4#21] opened 2017-08-30 19:11 UTC
Hey buddy this is Maurice I wanted to let you know that every time my buddy and I load up the sync helper we have trailers flying around in the sky landing in the middle of the road. And also my buddy and I keep having damage on our trucks just sitting in the parking lot picking and load out. Hope you solve this issue with the program soon so we can use it again. Thank you

**Comment by jorensanbar** [comment] 2017-10-29 18:43
Yes, The damage of the truck increases until it reaches 100%, this without even moving the truck.

**Comment by DaviMedrade** [comment] 2017-10-31 03:15
Does this always happen? Is it in a specific situation? Are you syncing with a trailer attached?

I haven't been able to reproduce this, and until I do I can't fix it, so I need to know what kind of scenario triggers the bug. It's really odd because the program doesn't change anything in the save file except for the job offers, so I can't even begin to guess what the cause of this problem is.

I'm guessing it's not a common occurrence, considering there's only been two reports in two months.

**Comment by jorensanbar** [comment] 2017-10-31 05:08
Yes, always happen, when I start the game > save the game > sync the jobs > and when load the save, the damage increases until it reaches 100%.

Check this: [https://youtu.be/qInZvO8ziMg](https://youtu.be/qInZvO8ziMg)

**Comment by DaviMedrade** [comment] 2017-10-31 05:35
I think some corruption might be happening during the sync process that misplaces the truck. It shouldn't happen since the truck isn't actually moved, but if for some reason it does and the truck ends up into the terrain, for example, that might explain the issue. Would you be able to upload your save before and after syncing?

1. Fix the truck and make sure the issue is not happening.
2. Save and sync.
3. Upload here the synced save file and the clean backup generated by the program. Since you seem to have only one profile and save, those files can be found in Documents\American Truck Simulator\profiles\\[hash of your profile]\saves\\[folder without “autosave”]. The files are game.sii and game.sii.raw.txt.

Thanks.

**Comment by jorensanbar** [comment] 2017-10-31 05:45
When I fix the truck with F7, because the truck does not move because of the damage, as soon as I leave the workshop menu, the damage starts to rise again.

[Original.zip](https://github.com/davidsantos-br/ETS2Sync-Helper-4/files/1429679/Original.zip)
[Synced.zip](https://github.com/davidsantos-br/ETS2Sync-Helper-4/files/1429680/Synced.zip)

**Comment by DaviMedrade** [comment] 2017-10-31 08:00
I wasn't able to load your save into my game (the game says it failed to load, probably because it detects it wasn't created with my profile).

I haven't been able to reproduce this at all. Using my own profile I never got any damage. I changed trucks, and tried moving to a couple different spots, but no damage at all, both online and offline.

Does the issue happen if you do it in the regular, offline game (i.e. without using TruckersMP)? Does it happen if you use the “Clear Jobs” button in ETS2Sync Helper, instead of “Sync Jobs”? I know you can't play in those scenarios, but it might help me pin down the set of circumstances that trigger this bug.

**Comment by jorensanbar** [comment] 2017-10-31 19:39
**- Does the issue happen if you do it in the regular, offline game (i.e. without using TruckersMP)?**
Yes, it happens in multiplayer and offline.

**-Does it happen if you use the “Clear Jobs” button in ETS2Sync Helper, instead of “Sync Jobs”?**
It happens only when the jobs are synchronized, when we press Clear Jobs or Reset Economy, the game returns to the normal jobs of the game, and the damage does not increase alone.

**I know you can't play in those scenarios, but it might help me pin down the set of circumstances that trigger this bug.**
Currently we are 15 active members in the company, that is equivalent to 15 different PC configurations, as well as 15 different profiles and saves, and in all the profiles exactly the same happens. As soon as the 600 hours are added to the jobs, the damage begins to rise exponentially.

I downloaded the Source Code, but it shows that it occupies many dependencies, (I only saw it quickly) and I did not have time to review deeply. I was going to try to check where the 600 hours come from, to reduce it to 30. Also check if the game time changes by the time zone.

I'm going to see if I get a profile to try, and that you can use it too.

**Comment by DaviMedrade** [comment] 2017-11-01 00:21
In that company, is there anything in common for everyone? A trip logging app or some DLC that everyone needs to have, or something like that?

Also, does the issue happen in ETS2 as well or only in ATS?

Regarding the source code, in order to compile it in Visual Studio you need to download and compile wxWidgets 3.1 and zlib (setting the environment variables WXWIN and ZLIBDIR to their respective directories), and install Ragel and GraphViz (ensuring that Ragel's ragel.exe and GraphViz's dot.exe are in your PATH).

**Comment by jorensanbar** [comment] 2017-11-02 05:17
Good evening David,

Right, we all use TrucksBook, but in the same way, even without opening the registration application, the problem continues.

These days I was doing tests, and it seems that I finally found the problem.

After synchronizing jobs for several days, and only using the MP, I had not slept, and I had not changed garage either because I only have a garage, and in MP, the driver does not suffer from fatigue.

Checking the status of the 4 employees that I have, I see that they have no earnings, that they are at $ 0 for the last 7 days, then I made a quick trip to my garage, and my employees already have earnings of 7 days. (My money went up suddenly)

I synchronize jobs, and I see that the damage goes up, but much more slowly, so I buy another garage, and start making quick trips between the garages. My money starts to rise, and when I synchronize jobs, I see that the damage stops increasing.

I'm going to tell my colleagues, before synchronizing, to make several quick trips between garages, to see if the change also affects them.

**Closed as completed** 2017-11-14 13:41 UTC
